server:
  port: 8080

jwt:
  secret: flashcart-super-secret-key-must-be-at-least-32-chars

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
      routes:
        - id: auth-service
          uri: http://flashcart-auth-service:8085
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth(?<segment>/.*|$), /api/auth${segment}

        - id: product-service
          uri: http://flashcart-product-service:8081
          predicates:
            - Path=/products,/products/**
          filters:
            - RewritePath=/products(?<segment>/.*|$), /api/products${segment}

        - id: order-service
          uri: http://flashcart-order-service:8082
          predicates:
            - Path=/orders,/orders/**
          filters:
            - RewritePath=/orders(?<segment>/.*|$), /api/orders${segment}

        - id: inventory-service
          uri: http://flashcart-inventory-service:8083
          predicates:
            - Path=/inventory,/inventory/**
          filters:
            - RewritePath=/inventory(?<segment>/.*|$), /api/inventory${segment}

        - id: notification-service
          uri: http://flashcart-notification-service:8084
          predicates:
            - Path=/notifications,/notifications/**
          filters:
            - RewritePath=/notifications(?<segment>/.*|$), /api/notifications${segment}

        - id: notification-ws
          uri: http://flashcart-notification-service:8084
          predicates:
            - Path=/ws/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      default-filters:
        - AddResponseHeader=X-Gateway, FlashCart-Gateway

management:
  endpoints:
    web:
      exposure:
        include: "*"